### ISSUE TITLE
io.github.sugakandrey#scala-compiler-indices-protocol_2.10;0.1.1: not found

### ISSUE THREAD

**Issue by travisltq** [JetBrains/intellij-scala-indices-protocol#1]
Please let me know if you need more information :)

sbt version: .13.18
IntelliJ IDEA 2019.1 (Ultimate Edition)
Build #IU-191.6183.87, built on March 27, 2019
JRE: 1.8.0_202-release-1483-b39 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.4

```

/Library/Java/JavaVirtualMachines/jdk1.8.0_191.jdk/Contents/Home/bin/java -agentlib:jdwp=transport=dt_socket,address=localhost:52248,suspend=n,server=y -Xdebug -server -Xmx1536M -Dhttp.proxyHost=proxy -Dhttp.proxyPort=8080 -Dhttps.proxyHost=proxy -Dhttps.proxyPort=8080 -Dproxy.authentication.username=***** -Dproxy.authentication.password=********* "-Dhttp.nonProxyHosts=nexus|*.*******|artifactory|git|upsource-*****" -XX:MaxPermSize=384M -Dhttps.proxyHost=localhost -Dhttps.proxyPort=3128 -Dhttp.proxyHost=localhost -Dhttp.proxyPort=3128 "-Dhttp.nonProxyHosts=nexus|*.local|*.******|10.*" "-Dhttps.nonProxyHosts=nexus|*.local|*.*****|10.*" -Dsbt.repository.secure=false -Dlogger.file=/Users/*****/conf/***/logback.xml -Dhttp.port=12345 -Dconfig.file=/Users/******/conf/*******.conf -Dsbt.repository.config=/Users/*****/.sbt/repositories -Didea.managed=true -Dfile.encoding=UTF-8 -jar "/Users/****/Library/Application Support/IntelliJIdea2019.1/Scala/launcher/sbt-launch.jar" --addPluginSbtFile=/private/var/folders/tb/gq95fkk141bdyg4ht529wrz19dyx4n/T/idea.sbt "; set ideaPort in Global := 49324 ; idea-shell"
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=384M; support was removed in 8.0
Listening for transport dt_socket at address: 52248
[info] Loading global plugins from /Users/***/.sbt/0.13/plugins
[info] Updating {file:/Users/****/.sbt/0.13/plugins/}global-plugins...
[info] Resolving com.eed3si9n#sbt-dirty-money;0.1.0 ...
[info] Resolving org.jetbrains#sbt-structure-extractor;2018.2.1+4-88400d3f ...
[info] Resolving org.jetbrains#sbt-idea-shell;2018.3 ...
[info] Resolving org.jetbrains#sbt-idea-compiler-indices;0.1.2 ...
[info] Resolving io.github.sugakandrey#scala-compiler-indices-protocol_2.10;0.1.1 ...
[info] Resolving io.github.sugakandrey#scala-compiler-indices-protocol_2.10;0.1.1 ...
[warn] 	module not found: io.github.sugakandrey#scala-compiler-indices-protocol_2.10;0.1.1
[warn] ==== typesafe-ivy-releases: tried
[warn]   http://repo.typesafe.com/typesafe/ivy-releases/io.github.sugakandrey/scala-compiler-indices-protocol_2.10/0.1.1/ivys/ivy.xml
[warn] ==== sbt-plugin-releases: tried
[warn]   http://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/io.github.sugakandrey/scala-compiler-indices-protocol_2.10/0.1.1/ivys/ivy.xml
[warn] ==== local: tried
[warn]   /Users/***/.ivy2/local/io.github.sugakandrey/scala-compiler-indices-protocol_2.10/0.1.1/ivys/ivy.xml
[warn] ==== artifactory-ivy: tried
[warn]   https://artifactory/artifactory/virtual-ivy/io.github.sugakandrey/scala-compiler-indices-protocol_2.10/0.1.1/ivys/ivy.xml
[warn] ==== artifactory-maven: tried
[warn]   https://artifactory/artifactory/virtual-maven/io/github/sugakandrey/scala-compiler-indices-protocol_2.10/0.1.1/scala-compiler-indices-protocol_2.10-0.1.1.pom
[warn] ==== intellij-scala-plugin: tried
[warn]   /Users/***/Library/Application Support/IntelliJIdea2019.1/Scala/repo/io.github.sugakandrey/scala-compiler-indices-protocol_2.10/0.1.1/ivys/ivy.xml

...

[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: io.github.sugakandrey#scala-compiler-indices-protocol_2.10;0.1.1: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn] 	Note: Unresolved dependencies path:
[warn] 		io.github.sugakandrey:scala-compiler-indices-protocol_2.10:0.1.1
[warn] 		  +- org.jetbrains:sbt-idea-compiler-indices:0.1.2 (scalaVersion=2.10, sbtVersion=0.13) (/private/var/folders/tb/gq95fkk141bdyg4ht529wrz19dyx4n/T/idea.sbt#L4-10)
[warn] 		  +- org.scala-sbt:global-plugins:0.0 (scalaVersion=2.10, sbtVersion=0.13)
sbt.ResolveException: unresolved dependency: io.github.sugakandrey#scala-compiler-indices-protocol_2.10;0.1.1: not found
	at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:320)
	at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:191)
	at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:168)
	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:156)
	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:156)
	at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:133)
	at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:57)
	at sbt.IvySbt$$anon$4.call(Ivy.scala:65)
	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:95)
	at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:80)
	at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:99)
	at xsbt.boot.Using$.withResource(Using.scala:10)
	at xsbt.boot.Using$.apply(Using.scala:9)
	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:60)
	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:50)
	at xsbt.boot.Locks$.apply0(Locks.scala:31)
	at xsbt.boot.Locks$.apply(Locks.scala:28)
	at sbt.IvySbt.withDefaultLogger(Ivy.scala:65)
	at sbt.IvySbt.withIvy(Ivy.scala:128)
	at sbt.IvySbt.withIvy(Ivy.scala:125)
	at sbt.IvySbt$Module.withModule(Ivy.scala:156)
	at sbt.IvyActions$.updateEither(IvyActions.scala:168)
	at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1555)
	at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1551)
	at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$122.apply(Defaults.scala:1586)
	at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$122.apply(Defaults.scala:1584)
	at sbt.Tracked$$anonfun$lastOutput$1.apply(Tracked.scala:37)
	at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1589)
	at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1583)
	at sbt.Tracked$$anonfun$inputChanged$1.apply(Tracked.scala:60)
	at sbt.Classpaths$.cachedUpdate(Defaults.scala:1606)
	at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1533)
	at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1485)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by elvircrn** [comment]
@travisltq How did you manage to resolve this?

**Comment by coryfklein** [comment]
# My Solution

Disconnect from your VPN

# Explanation

I saw this same issue when trying to reload my sbt project in IntelliJ over my company's VPN. The Maven project referenced above certainly does exist - see https://repo1.maven.org/maven2/io/github/sugakandrey/scala-compiler-indices-protocol_2.12/0.1.1/scala-compiler-indices-protocol_2.12-0.1.1.pom

When I visited that URL directly while on my company VPN I got this message:

<img width="591" alt="image" src="https://user-images.githubusercontent.com/3503322/70167213-781e4d00-1683-11ea-8bbb-d686d26a0145.png">

But when I turned off my VPN it worked just fine. Makes sense - their autobanning functionality they have turned on was likely triggered by my whole company using Maven, apparently all from a single IP possibly. Simply turning off my VPN allowed IntelliJ's sbt to get past the error.

**Comment by elvircrn** [comment]
Thanks for the explanation!
